name: puduu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  drift: ^2.35.0
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  intl: ^0.20.3
  riverpod: ^3.4.3
  supabase_flutter: ^2.17.2
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
